# Generated by Django 4.2.1 on 2023-05-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(default='778899', max_length=6)),
            ],
            options={
                'db_table': 'pin',
            },
        ),
    ]
