# Generated by Django 4.1.9 on 2023-06-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(default='778899', max_length=6)),
            ],
            options={
                'verbose_name': 'PIN',
                'verbose_name_plural': 'PIN',
                'db_table': 'pin',
            },
        ),
    ]
