# Generated by Django 4.2.1 on 2023-05-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'verbose_name': 'PIN', 'verbose_name_plural': 'PIN'},
        ),
    ]
