# Generated by Django 4.2.1 on 2023-05-29 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='is_used',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is Used'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Ticket Name'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Ticket ID'),
        ),
    ]
