# Generated by Django 4.1.9 on 2023-06-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickets_authorization_tickets_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketsClassChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Class Name')),
                ('seats', models.IntegerField(default=0, verbose_name='Number of Seats')),
            ],
            options={
                'verbose_name': 'Ticket Class Plus',
                'verbose_name_plural': 'Tickets Class Plus',
                'db_table': 'tickets_class_child',
            },
        ),
        migrations.AddField(
            model_name='tickets',
            name='ticket_class_child',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.RESTRICT, to='tickets.ticketsclasschild'),
        ),
    ]
