# Generated by Django 4.1.9 on 2023-06-03 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketsused_time_used_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='phonenumber',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0899999999'. Up to 16 digits allowed.", regex='^\\0?1?\\d{9,16}$')], verbose_name='Mobile Number'),
        ),
    ]
