# Generated by Django 4.2.1 on 2023-05-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_tickets_is_used_alter_tickets_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
